### ISSUE TITLE
Clarification on what FFImageLoading does different?

### ISSUE THREAD

**Issue by fschwiet** [alexrainman/CarouselView#179]
The documentation states:

> If you have memory leaks in Android when using the Carousel with images, it's not the control
> itself. It's Xamarin Android not handling images correctly.  To solve the problem you can use FFImageLoading...

Could you give any clarification on what FFImageLoading does differently than Xamarin.Android's image control? 

I've observed:
* When FFImageLoading hits OOM trying to render an image, it will not crash the app but rather just not show the image (an improvement for us).
* FFImageLoading has functionality to cache downloaded images (not relevant to us, all our images are sent with the app).

I was just hoping to capture what you learned about the two image controls.  We're seeing memory pressure in other parts of our app, and I would like to be able to identify where/if FFImageLoading would help those.  Also we've ran into a lot of problems using OxyPlot within CarouselView (Oxyplot has a lot of coupling between its PlotModel and PlotView, we have some weird code in their to keep it from crashing).  I'm hoping that by understanding how FFImageLoading behaves better I will have better perspective for anticipating issues with OxyPlot.

**Comment by alexrainman** [comment]
FFImageLoading does what Xamarin.Android doesn't. For example, imagine you want to load an image from sdcard. The image is way bigger in dimensions comparing to the placeholder where you are going to show it. If you do plain Xamarin.Android, the entire big image will be loaded in memory no matter the size of the UI container. FFImageLoading downsize and down sample the image for you on the fly, but also do a better memory cleaning for you. Also, if you are using the same image in different places, the library share it instead of loading multiple instances. Cool uh?

**Comment by fschwiet** [comment]
Ok, thank you.
