### ISSUE TITLE
It does not work without setting HeightRequest

### ISSUE THREAD

**Issue by 207713** [alexrainman/CarouselView#194]
Is there any way to make this dynamic, according to content height?

**Comment by alexrainman** [comment]
I don't know how you are using it but there's no need for HeighRequest. Can you provide an example?

**Comment by 207713** [comment]
thank you for the fast response, here is the issue:

with heightrequest: [http://i.imgur.com/hiEH5MM.jpg](url)
without heightrequest: [http://i.imgur.com/4zyQoIf.jpg](url)

**Comment by alexrainman** [comment]
Whats the rest of the xaml? I mean, whats is wrapping the Carousel?

**Comment by alexrainman** [comment]
Actually, it depends on the content you are using the Carousel. If you are using StackLayout, of course you need HeightRequest or how the control will know? It adapts to grid rows with height set to * or auto.

**Comment by jeromeliger** [comment]
I'm sorry but I'm in the same case... and if I don't set the "heightRequest" of the carouselview, it fill all the screen area...

To prop my said, I've done a simple test :

So I've create a new test page, to confirm the correct "auto height rendering" of my "WeekView" (this view that is used later in my carousel as the Template) :

    <ContentPage.Content>
    	<Grid ColumnSpacing="0" RowSpacing="0" Margin="0" Padding="2" BackgroundColor="#ff003c61">
    		<Grid.RowDefinitions>
    			<RowDefinition Height="auto"/>
    			<RowDefinition Height="*"/>
    		</Grid.RowDefinitions>
    		<views:WeekView Grid.Row="0"/>
    		<StackLayout Grid.Row="1" BackgroundColor="Red"/>
    	</Grid>
    </ContentPage.Content>

And the result is OK, my "WeekView" adapt it size to the content (NavigationBar Before, and Red Layout After) :
![testpage](https://user-images.githubusercontent.com/3584319/32648731-7f8d5b5a-c5f7-11e7-91a8-7e373936db0e.png)

But if I define this "WeekView" as my carousel Template, and put the carouselview in the same "Grid Architecture" :

    <ContentPage.Content>
    	<Grid ColumnSpacing="0" RowSpacing="0" Margin="0" Padding="2" BackgroundColor="#ff003c61">
    		<Grid.RowDefinitions>
    			<RowDefinition Height="auto"/>
    			<RowDefinition Height="*"/>
    		</Grid.RowDefinitions>
    		<controls:CarouselViewControl 
    			x:Name="CarouselWeek"
    			Orientation="Horizontal"
    			ShowIndicators="False"
    			InterPageSpacing="2"
    			IsSwipingEnabled="true"
    			Position="{Binding CarouselWeekPosition}"
    			ItemTemplate="{Binding CarouselWeekTemplate}"
    			ItemsSource="{Binding WeekViewModels}"
    			PositionSelected="CarouselWeek_PositionSelected"
    			Grid.Row="0"
    			HeightRequest="100"
    			/>
    		<StackLayout Grid.Row="1" BackgroundColor="Red"/>
    	</Grid>
    </ContentPage.Content>

- With HeightRequest :
![withheight](https://user-images.githubusercontent.com/3584319/32650062-a4efbd34-c5fc-11e7-86e8-5f52158f13b4.png)

- Without HeightRequest :
![withoutheight](https://user-images.githubusercontent.com/3584319/32650072-aa727e54-c5fc-11e7-9d5c-ed7112700817.png)


I've tried to set the carousel "VerticalOptions" to "Start", "Center" or anything else... nothing better.

Any idea why it doesn't "auto-height" correctly ?
Is this due to carousel templates using ?

Easy to reproduce (if not, there is my sample code)
[TestCalPCL.zip](https://github.com/alexrainman/CarouselView/files/1460641/TestCalPCL.zip)

CarouselView.FormsPlugin V4.4.6
Xamarin.Forms V2.4.0.38779
