### ISSUE TITLE
UWP: crash on window resize

### ISSUE THREAD

**Issue by freever** [alexrainman/CarouselView#199]
Hi Alex

Thanks for this control, I think it's going to open up a lot of options for us on the layout front. 

One issue I've run into, both in my app and in the Demo.UWP MainPage, is that resizing the window causes a crash. Horizontal scaling seems to work OK, if a little laggy, but vertical scaling causes an immediate crash with an unhelpful "Unspecified Error" exception message from somewhere in UWP's reptile brain.  

It sounds like it's in the same general area as #7 - are you on top of this one? 

Thanks again,
Adrian

**Comment by EdenCerberus** [comment]
Hi Alex,

I have the same problem like freever since several weeks.

The hole carousel seems to reload and reconstruct all my dynamically created pages and it takes 3 to 5 seconds (depending on the itemssource-count) including the crash freever mentions above.

In my case this behavior is a pretty big problem, cause the Virtual Keyboard triggers resizing.

I have downloaded an older version of your carousel some weeks ago, to disable the Page-indicator-dots (which causes crashing on PageLoad, even with ShowIndicators="false").

I hope there's a fast solution for the problem. If you need to know more, let me know and I'll provide more detailed information.

Thank you and best Regards
Alex W.

**Comment by alexrainman** [comment]
Guys, i have been busy but i'm back to take care of all the issues. Expect news soon.

**Comment by alexrainman** [comment]
Don't know how to fix this yet.

**Comment by jalbertSyncroTech** [comment]
I'm having a similar issue, and I think I've tracked down the culprit.  I've submitted a bug on the Xamarin.Forms github.
Xamarin.Forms UWP ButtonRenderer UpdateContent() ImageOpened event NullReferenceException #1423
https://github.com/xamarin/Xamarin.Forms/issues/1423

**Comment by panchow** [comment]
I have experienced similar issue.  I have a UWP application that is a file browser.  In the list view, I list all files in a folder.  When I resize the UWP window and the list is big, it hangs the entire Windows OS, not just the UWP app.
