### ISSUE TITLE
[UWP] Intermittent bug where carousel content does not render in 4.4.3

### ISSUE THREAD

**Issue by mattrichnz** [alexrainman/CarouselView#209]
Thanks @alexrainman for restoring the _VirtualizingStackPanel_ to fix the regression in 4.4.1.
However, we have found 4.4.3 has intermittent rendering issues on UWP.

What happens? Intermittently the carousel content does not display, and only appears when you resize the window. Rolling back to 4.4.0, this bug does not occur.

**Comment by alexrainman** [comment]
I cannot reproduce this. Can you provide a demo project?

**Comment by predalpha** [comment]
I encounter this issue on some pages with the carousel control on UWP.
It's very strange and im not able to understand the reason.

Moreover when my window goes to fullscreen, Carousel position goes to 0. 
Back to 4.4.0.

**Comment by ac2112** [comment]
I also have the same problem.  Resizing works.  Sorry, can't give you the project.  As mattrichnz said, it's intermittent.

**Comment by mattrichnz** [comment]
Same problem as described. As mentioned, had to roll back to 4.4.0 for stability.

**Comment by alexrainman** [comment]
I will keep running some test to see if i can reproduce this.

**Comment by alexrainman** [comment]
I cannot reproduce this.

**Comment by rdaniel0** [comment]
I'm able to reproduce this bug on UWP with 4.4.6

What I've determined so far, is that the carousel and some layouts within are rendering, but views like labels and such do not render.

I've attached a sample test project where I gave the carousel's layout a background color so you can see it's there, but it's children do not appear until you resize the window or force the view to render again (switching pages back and forth or something).

[CarouselViewNotRender.zip](https://github.com/alexrainman/CarouselView/files/1435861/CarouselViewNotRender.zip)

**Comment by schovan** [comment]
I have the same problem. Anyone has hotfix for this (call some refresh somewhere, etc...)?

**Comment by jelle-vdst** [comment]
I'm experiencing the same Bug in UWP with 4.4.6. The bug does not occur when i scroll, but only happens when i set the Carousel.Position from code (from some buttons i use as tabs).

The strange thing is, this only happens the first time, when i click on another button to switch to another position in the carousel, everything works. Or if i scroll, before clicking any button, everything will work as expected beyond that point. (also like other cases here, if i resize my window, the content appears)
(Note: the Position i navigate too from code, has to be different from the first and second position for the bug to occur)

Currently i use a hacky fix in my buttons event to make things work:
first i set Carousel.Position = ThePositionIWant -1
then Carousel.Position = ThePositionIWant
If i do this, everything will work as expected, but this is far from optimal ofcourse.

**Comment by alexrainman** [comment]
Guys, what about latest version? I will be releasing version 5.1 today.

**Comment by jelle-vdst** [comment]
I cannot test version 5.1 since you've upgraded to netstandard 2.0 and my project needs netstandard 1.4
However, i can confirm the issue is still present in 5.0.2
