### ISSUE TITLE
Support for Windows UWP

### ISSUE THREAD

**Issue by ravensorb** [alexrainman/CarouselView#3]
Any thoughts/plans on adding support for Windows UWP?

**Comment by alexrainman** [comment]
I am testing FlipView widget on UWP :)

**Comment by PierreJung** [comment]
Do you think this will come soon?

**Comment by alexrainman** [comment]
Workin on it :)

**Comment by JimSEOW** [comment]
Any update on UWP?

**Comment by alexrainman** [comment]
It will be released later this week.

**Comment by alexrainman** [comment]
Still working on it. Testing on simulator as i dont have a real Windows Phone device :(

**Comment by alexrainman** [comment]
This has been tricky. UWP DataTemplate doesn't have constructors with parameters, something like DataTemplate(Func<object>) could be useful here but doesn't work like that. You cannot assign DataTemplate content programmatically neither. Anyway, i am close. I was able to convert Xamarin.Forms view to UWP native element and add it to the control. Now i am wrapping the whole thing. Stay tuned. I also have Page Indicators in my roadmap.

**Comment by alexrainman** [comment]
UWP is out.

**Comment by alexrainman** [comment]
As i am not UWP expert, im having hard times making it work the right way. Actually, this plugin is the very first thing i do for the platform, so you are free to clone the repo and try to achieve this:

- Avoid to rebuild multiple times when ResizeChanged is called (maybe resize each page instead of re-generating them)

- Use UWP TemplateSelector that will return what Xamarin.Forms template selector will return given the position.

If you take a look at my code, i had to generate all the pages and add them to an array of FrameworkElement and use the array as source of FlipView. That's not the case of iOS and Android where only 3 pages are rendered at a time as maximum. I use each platform widget virtualization in those cases.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
