### ISSUE TITLE
Why dependency on XF 2.5?

### ISSUE THREAD

**Issue by scastria** [alexrainman/CarouselView#323]
If this is going to be the standard/official CarouselView component for Xamarin.Forms development, I think we need support for older versions of Xamarin.Forms.  XF 2.5 has lots of new bugs that make it unusable for some of us so we can't use this control since this control's nuspec has a dependency on XF 2.5.

If we point to on older version of this component to avoid the XF 2.5 dependency, then we miss all the bug fixes you are doing.

Can you lower the dependency version for XF or something?

**Comment by adrianknight89** [comment]
Honestly, I would not be surprised if this was kept on the back burner for at least another 6 months. `CarouselView` is not on their [official roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap) yet. I agree about the dependency issue though it'll require more testing with different XF versions. Not sure if Alex has the resources and time to make that kind of commitment.

**Comment by alexrainman** [comment]
CarouselView is on XF Roadmap. They asked me to target master branch on the PR, which i will be doing this weekend and im done with this. Once it is included in XF, im out. You are right, i dont have the time and resources anymore. I think my job is done and i took this to the highest level i can. Thanks

**Comment by scastria** [comment]
i commend you for your efforts.

**Comment by adrianknight89** [comment]
@alexrainman Thanks for your work, man. This is going to be a popular control once it's merged. It was on their forum roadmap, but I wonder why it wasn't included on the Git wiki? 

Also, correct me if I'm wrong, but, once it's part of XF, there won't be a way to have this on older versions of XF because it will only be available on versions 2.5 and up, so the dependency on 2.5 makes sense. @scastria How can you introduce a feature on 2.5 and make it available to previous versions at the same time? Doesn't make sense to me.

If you're talking about making the third party Nuget compatible with previous versions, once this repository is archived, there won't be any further work on it. So, over time, the package will be outdated. Unless XF team maintains various controls as separate packages, `CarouselView` will have dependency on 2.5.

Have a good weekend.
