### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by Andy747** [alexrainman/CarouselView#433]
Hi,
I have a problem with the code below, which throws a "Common Language Runtime detected an invalid program" error, when ever I compile the code.
The interesting thing is when I remove the "Clicked="Btn_Clicked"" from the button element, everything works perfect.

Any ideas why this would be throwing this error?

What I am trying to do is to have some informational information displayed that the user can swipe between. Also I want to have a next and back button that will move the carousel between the different views.

Any help would be greatly appreciated.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
             x:Class="Impakt_App.Pages.TestPage">
    <ContentPage.Content>
        <cv:CarouselViewControl >
            <cv:CarouselViewControl.ItemsSource>
                <x:Array Type="{x:Type Grid}">

                    <Grid>
                        <Label>test</Label>
                    </Grid>

                    <Grid>
                        <Button Text="Test Button" Clicked="Btn_Clicked"></Button>
                    </Grid>

                </x:Array>
            </cv:CarouselViewControl.ItemsSource>
        </cv:CarouselViewControl>
    </ContentPage.Content>
</ContentPage>`

**Comment by PieterjanDeClippel** [comment]
I'm also having this issue.
It's because there's an eventbinding to a button inside the carousel.
When you would remove the eventbinding, your app would actually build.

eg change:
`<Button Text="Test Button" Clicked="Btn_Clicked"></Button>`
to
`<Button Text="Test Button"></Button>`
and the problem disappears.

Off course this gets me nowhere, since there's no other way to bind the event.
I also tried the event binding through c#, but somehow the button is just NULL.
I'll try to make an issue with demo, and let's hope the problem will be solved by the developers of this package.

**Comment by PieterjanDeClippel** [comment]
I've uploaded an example to [my webserver](http://pieterjan.pro/CarouselViewIssue.zip).
This app is not building. Remove the Clicked event handler and the app will build.
It would be greatly appreciated if this issue gets solved.

Cheers,
Pieterjan

**Comment by alexrainman** [comment]
I am not able to find out why this happens. It should be an internal Xamarin.Forms issue.

As a workaround, try using a Command binding:

```
<Button Text="Click me!" Command="{Binding OnClicked}"/>
```
