### ISSUE TITLE
Error serious issue

### ISSUE THREAD

**Issue by lumisoftusa** [alexrainman/CarouselView#435]
Hi iam using CarouselView with great success but iam suddenly facing this streange error this is the error report from Hockey app . Iam using Xamrin forms.

Error details are give below.

I am very disturb because i replaced the another Carousel with this and whole apps is disturb with this error.

** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x11693f4f0; frame = (0 0; 371 474.4); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x115f5c970>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x115aecc40>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x117a436e0>.'

**Comment by ivanxamarin** [comment]
I guess you're using Views in ItemsSource. It seems that it's not working yet for a few reasons. You should go for some alternatives as DataTemplates and TemplateSelector if that's the case.

I hope ItemsSource will work as soon as the Carousel becomes the part of Forms since it's just natural way to create tabbed views.

**Comment by lumisoftusa** [comment]
Yap I have figured out the issue and now Iam in good position.

Iam closing this issue but just guide me how can add beautiful animation between pages on swapping there is an animation property but it is not producing animation.
