### ISSUE TITLE
[Android] CarouselView not refreshing after updating ItemSource property. Showing blank.

### ISSUE THREAD

**Issue by sachinkanadia** [alexrainman/CarouselView#480]
Hi There,

I am using the following versions:
CarouselView.FormsPlugin 5.2.0
Xamarin.Forms 3.1.0.697729

When using the Carousel View on Android it works fine when displaying initially, however when updating the ObservableCollection (which the Carousel Views ItemSource is bound to) it shows a blank screen. It looks like the ObservableCollection has nothing in it, however when debugging the code the ObservableCollection has items in it. On iOS the same code works perfectly. Here is the ObservableCollection:

private readonly ObservableCollection<JourneyModel> _Journeys = new ObservableCollection<JourneyModel>();

        public ObservableCollection<JourneyModel> Journeys
        {
            get
            {
                return _Journeys;
            }
        }

I am calling OnPropertyChanged(nameof(Journeys)); in another method.

**Comment by alexrainman** [comment]
?

**Comment by sachinkanadia** [comment]
Hi Alex,

Sorry to be a pest. But do you have any idea as to when this issue would be looked at?

**Comment by zFadil995** [comment]
Hi, 

I am having a very similar problem, my carousel is initially empty (The binded list is null), but when I update it it doesn't show on UI, although debugging shows that CarouselView indeed has an ItemSource with the correct number of items. 

Reloading the whole page is the only workaround available, but is not acceptable (or smart).

P.S. I have tried using both lists AND observable collections, as well as changing ItemsSource during code execution, but nothing's helping.

Also, seems exclusive to Android.

**Comment by zFadil995** [comment]
To add on top of that, this happens on verison 5.2.0, with X.F. 3.3.0.967583.

A random idea brought me to test it with older versions, and this problem doesn't seem to appear at all in version 4.4.6. The first version where I am seeing it is 5.0.0.

Hope that is useful information.

P.S. I will probably be unable to create a MCV example, but I might be able to share the offending pages in private messaging, if you choose to contact me.

**Comment by sachinkanadia** [comment]
Hi zFadil995,

Using version 5.0.2 is a sensible workaround for the time being.
Thank you for highlighting this.

**Comment by alexrainman** [comment]
@zFadil995 so, you start with a null ItemsSource and then you change it at runtime no?

**Comment by zFadil995** [comment]
@alexrainman exactly. The view is part of the page, but is one of many widgets and it is initially hidden. After logging in, the property containing the source is populated (it is a part of user data, in this case a list of accounts) and the widget is shown on the screen.

The actual behaviour is rather peculiar to be honest, because besides redrawing the page making it work properly after logging in, redrawing the page while the ItemSource is still null, and then changing it, seems to fix the problem.

Also, logging out, and logging back in, (which does a number of things, including switching visibility and updating the ItemSource again) fixes the problem as well.

For the time being, I have 5.2.0 installed on my portable and iOS project (because of the implementation of IsSwiping that fixes an application crash on iOS), and 5.0.2 on Android.

I have some time at the moment, so if that is not enough information please tell me, so I can try to make a small reproducible project for you.

**Comment by alexrainman** [comment]
Ah, now I get what's the issue.

The problem is that CarouselView needs to know its size so it can assign it to its children and, as it is hidden there's no size assigned.

Workaround: add the carousel programmatically after a successful login when you have the items to be used as source.

**Comment by zFadil995** [comment]
I have actually tried doing that, in multiple ways. Simply adding it to a wrapper view (empty StackLayout) didn't work, and other ways ended up being detrimental to performance.

Also, the view holding the CarouselView has a fixed height, the carousel itself has one, as well as the Children populating DataTemplate. 

As I mentioned, this only happens on Android devices, not iOS, and only after v5.0.2. To my best knowledge, it doesn't even happen on all of the devices I have tested on, but only some of them (and on some it is consistent, but there is no common ground amongst them, one is a Sony M4, other a Huawei P20, while it works just fine on some knockoffs and higher-end devices like the Note 8).

I could try adding it programatically again, but I am trying to avoid that since the main view is rather big, and precompiled xaml is a significant factor in performance.

**Comment by alexrainman** [comment]
@zFadil995 carouselview behavior doesn't change if you add in xaml with pre-compilation enabled as the native control is created at runtime.

So, your best choice is adding it programmatically to its container. Also, I advice to use a Grid instead as container. StackLayout has some weird behavior with height request that mess with the carousel view.

**Comment by alexrainman** [comment]
Can you share small demo reproducing the issue?

**Comment by sachinkanadia** [comment]
Hi Alex,

Thanks for looking into this. Please let me know when I can update my project to your latest release with the fix, confirming the version number.

Thanks Sachin

**Comment by alexrainman** [comment]
@sachinkanadia next release, which includes around 10 brand new functionality, will be released early January.

One catch: it will require a license.

Some may not agree with me on that but, I cannot maintain this project for free anymore. It will not be expensive though.

I did a big code refactoring and fixed more than 50 bugs so, it will be very stable, focused on performance and requested functionality, and support for vastest Xamarin.Forms packages.
