### ISSUE TITLE
[Android/iOS] Strange problems when rendering views

### ISSUE THREAD

**Issue by badstorm** [alexrainman/CarouselView#497]
Hi, 
i have this strange problem on both Andorid (9) ad iOS (12). This is my situation:

The CarouselView render a customview with a StackLayout inside. As ItemSource i pass a List<MyObject> with a custom object that has information like image, title and so on. 
In that view, i override OnBindingContextChanged and i get the current MyObject instace. Than I start add views like Image and Label to the StackPanel of the custom view. The logic works but this is what I get: https://youtu.be/9WE1rAxS144

Do you have any ideas on what is wrong?

Thanks in advance.

**Comment by dfoulk** [comment]
I did something similar (identical perhaps) to what you're trying to do. I reviewed my implementation and see a couple of things that I had done to get it working with this plugin.

### First
I used code for this page (instead of XAML), which I wouldn't have done unless necessary (for one reason or another). Maybe convert your XAML to code if the next suggestion doesn't work on it's own...?

### Second
Try adding the following (it's a long shot, but may work):

```csharp
        protected override void OnSizeAllocated(double width, double height)
        {
            // Event handler that's fired when the size of the element is set during a layout cycle (i.e. user rotates device from portrait to landscape)

            //// Only run on Android
            //if (Device.RuntimePlatform != Device.Android)
            //    return;

            // IMPORTANT: Only run if the new dimensions (post-rotation) are noticeably different than the previous dimensions (pre-rotation)
            if (Math.Abs(width - _width) < 0.1 && Math.Abs(height - _height) < 0.1)
                return;

            // Store the new width (for future comparisons)
            _width = width;
            _height = height;

            // Redraw the page
            Init();

            base.OnSizeAllocated(width, height);
        }
```

### Third
Are you using Xamarin.FFImageLoading.Forms? If so, make sure you've reviewed the documentation and configured the plugin properly. (https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API)

I've battled with this plugin a couple of times with Xamarin.Forms 3.x and there are some quirks to work through. If these suggestions don't work for you, please let me know and I will do my best to help!

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. More info needed in case this issue is not solved.

**Comment by dfoulk** [comment]
@alexrainman that's great to hear man! What kind of info would you need here. I'll try to provide what I can.

**Comment by alexrainman** [comment]
@dfoulk maybe a repro solution?

**Comment by dfoulk** [comment]
> @dfoulk maybe a repro solution?

After reading the OP's post (and my own) again, I don't have repro steps for his issue. My issue was the same as #157, which seems to have been closed.

My bad!

**Comment by alexrainman** [comment]
Unless you tell StackLayout its size, you will have this kind of behavior. Nothing i can do in this case.
